application: notifrytest
version: 2
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /static
  static_dir: static
  secure: always
- url: /admin/.*
  script: admin.py
  login: admin
  secure: always
- url: /.*
  script: index.py
  secure: always
