application: notifrytest
version: 3
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /(favicon\.ico)
  static_files: static/\1
  upload: /(favicon\.ico)
- url: /static
  static_dir: static
  secure: always
- url: /admin/.*
  script: admin.py
  login: admin
  secure: always
- url: /.*
  script: index.py
  secure: always
